/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as PassportRouteImport } from './routes/passport'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evidence': typeof EvidenceRoute
  '/matches': typeof MatchesRoute
  '/passport': typeof PassportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evidence': typeof EvidenceRoute
  '/matches': typeof MatchesRoute
  '/passport': typeof PassportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evidence': typeof EvidenceRoute
  '/matches': typeof MatchesRoute
  '/passport': typeof PassportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/evidence' | '/matches' | '/passport'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/evidence' | '/matches' | '/passport'
  id: '__root__' | '/' | '/evidence' | '/matches' | '/passport'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvidenceRoute: typeof EvidenceRoute
  MatchesRoute: typeof MatchesRoute
  PassportRoute: typeof PassportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvidenceRoute: EvidenceRoute,
  MatchesRoute: MatchesRoute,
  PassportRoute: PassportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
